In [2]:
#Initialize Otter

import otter
grader = otter.Notebook("DSA2024Test.ipynb")

## DSA 2024 Summer School Admittance Check

Thanks for your interest in attending DSA 2024 Nyeri, Kenya. To attend the summer school you have to have some level of basic Python proficiency. Completing the following notebook should ensure you have the right kind of background to benefit maximally from the Summer School. See you in Nyeri!

In [64]:
import pandas as pd
import numpy as np
%matplotlib inline
import otter

grader = otter.Notebook()

**Question 1:** write a function `isValid(s)` that takes as argument a string s containing a sequence of parenthesis '(', ')', '{', '}', '[' and ']', and  determines if the input is valid. A input string is valid if for every open parenthensis there is a close one and parenthesis is well-formed. e.g  "(){}[]" is valid.

In [16]:
def isValid(s: str) -> bool:
    stack = []
    mapping = {')': '(', '}': '{', ']': '['}
    
    for char in s:
        if char in mapping:
            top_element = stack.pop() if stack else '#'
            if mapping[char] != top_element:
                return False
        else:
            stack.append(char)
    
    return not stack

# Test the function
print(isValid("(){}[]"))  # Output should be True


True


In [17]:
grader.check("q1")

q1 results: All test cases passed!

**Question 2:** Given a paragraph as a string, write a function that return the number of character with odd frequencies. E.g The paragraph ``DSA 2024 Nyeri`` has *10* characters with odd frequencies. i.e the entire frequency count is given as {' ': 2, '2': 2, 'D': 1, 'S': 1, 'A': 1, '0': 1, '4': 1, 'N': 1, 'y': 1, 'e': 1, 'r': 1, 'i': 1}) and there are *10* characters with odd frequences. So the function should return *10*. 

In [ ]:
def oddFrequencyCounter(theParagraph):
    char_count = {}
    for char in theParagraph:
        char_count[char] = char_count.get(char, 0) + 1
    odd_count = sum(1 for count in char_count.values() if count % 2 != 0)
    return odd_count

# Test the function
print(oddFrequencyCounter("DSA 2024 Nyeri"))  # 10


10


In [7]:
grader.check("q2")

q2 results: All test cases passed!

**Question 3:** Write an infinite generator function `odd_squares_sum` that yields the sum of square of odd numbers. e.g $1^2 + 3^2 + 5^2 + ...$ up to a ``limit``

In [4]:
def odd_squares_sum(limit):
    total = 0
    num = 1
    while True:
        total += num ** 2
        yield num ** 2
        num += 2
        if num >limit:
            break

# Testing
limit=100
sum_generator = odd_squares_sum(limit)
for value in sum_generator:
    print(value)



1
9
25
49
81
121
169
225
289
361
441
529
625
729
841
961
1089
1225
1369
1521
1681
1849
2025
2209
2401
2601
2809
3025
3249
3481
3721
3969
4225
4489
4761
5041
5329
5625
5929
6241
6561
6889
7225
7569
7921
8281
8649
9025
9409
9801


In [5]:
grader.check("q3")

q3 results: All test cases passed!

**Question 4:** Using the `odd_squares_sum` generator defined above, create a list of sum of squares up to a limit of $20$ and store the results in a numpy.array variable called `oddSumList` 

In [8]:
limit = 20
#The np.fromiter function takes an iterable (in this case, the generator odd_squares_sum(limit)) and a data type (dtype=int) and creates a NumPy array from the yielded values.
oddSumList = np.fromiter(odd_squares_sum(limit), dtype=int)

# Testing
print(oddSumList)



[  1   9  25  49  81 121 169 225 289 361]


In [9]:
grader.check("q4")

q4 results: All test cases passed!

**Question 5:** Compute the element-wise remainder of ``oddSumList`` when divided by $5$ and merge it with ``oddSumList``. The final output stored in the variable `mergedList` should be in the form of a list of tupples e.g ``[(1,1), (4,9), (0,25), ...]`` 

In [26]:
remainder_list = oddSumList % 5
mergedList = list(zip(remainder_list, oddSumList))

# Testing
print(mergedList)





[(1, 1), (4, 9), (0, 25), (4, 49), (1, 81), (1, 121), (4, 169), (0, 225), (4, 289), (1, 361)]


In [27]:
grader.check("q5")

q5 results: All test cases passed!

**Question 6:**  Write a function `greatest_common_divisor` that takes two inputs `a` and `b` and returns the greatest common divisor of the two numbers. E.g. input `(10, 15)` would return `5`

In [47]:
def greatest_common_divisor(a, b):
    while b:
        a, b = b, a % b
    return a

# Test the function
print(greatest_common_divisor(10, 15))  # Output: 5
print(greatest_common_divisor(15, 20))


5
5


In [48]:
grader.check("q6")

q6 results: All test cases passed!

**Question 7:**  Write a function `get_3_nearest` that takes in a point of interest ``pt`` and a **list** of points ``ptlist``  and returns a list of 3 nearest points from the point of interest ``pt``. Assume the distance between any two point is defined by the `L1-norm`.

In [30]:
#We'll calculate the Manhattan distance (L1-norm) between the point of interest and each point in the list.
#Then, we'll sort the points based on their distances and return the 3 nearest ones.
def get_3_nearest(pt, ptlist):
    sorted_points = sorted(ptlist, key=lambda x: abs(x[0] - pt[0]) + abs(x[1] - pt[1]))
    return sorted_points[:3]

# Testing
print(get_3_nearest((0, 0), [(1, 1), (2, 2), (-1, -1), (3, 3)]))



[(1, 1), (-1, -1), (2, 2)]


In [31]:
grader.check("q7")

q7 results: All test cases passed!

**Question 8:**  Write a function `diagonal_vector(M)` that returns a **numpy** array of the list of **absolute** values of the main diagonal entries in the matrix $M$

In [55]:
def diagonal_vector(M):
    return np.abs(np.diag(M))

# Test the function
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(diagonal_vector(M))  # Output: [1 5 9]


[1 5 9]


In [56]:
grader.check("q8")

q8 results: All test cases passed!

**Question 9:**  Write a function `flatten_reverse_lists` that takes in a list of lists and outputs a **reverse** sorted list of elements of sublists of the input list (confusing right?) <br>
Example: given `flatten_reverse_lists([[2,13,44], [6,7]])` it should return `[2,6,7,13,44]`

In [58]:
def flatten_reverse_lists(superlist):
    flattened_list = [element for sublist in superlist for element in sublist]
    return sorted(flattened_list, reverse=True)

# Test the function
print(flatten_reverse_lists([[2, 13, 44], [6, 7]]))  # Output: [44, 13, 7, 6, 2]


[44, 13, 7, 6, 2]


In [59]:
grader.check("q9")

q9 results: All test cases passed!

**Question 9:** Create a DataFrame mirroring the table below and assign this to `data`. 

| flavor | scoops | price |
|-----|-----|-----|
| white chocolate | 1 | 2 |
| vanilla | 1 | 1.5 |
| dark chocolate | 2 | 3 |
| strawberry | 1 | 2 |
| strawberry | 3 | 4 |
| vanilla | 2 | 2 |
| mint | 1 | 4 |
| mint | 2 | 5 |
| white chocolate | 3 | 2 |
| dark chocolate | 3 | 3 |
| white chocolate | 2 | 2 |
| dark chocolate | 5 | 3 |


In [32]:
import pandas as pd

data = pd.DataFrame({
    'flavor': ['white chocolate', 'vanilla', 'dark chocolate', 'strawberry', 'strawberry', 
               'vanilla', 'mint', 'mint', 'white chocolate', 'dark chocolate', 
               'white chocolate', 'dark chocolate'],
    'scoops': [1, 1, 2, 1, 3, 2, 1, 2, 3, 3, 2, 5],
    'price': [2, 1.5, 3, 2, 4, 2, 4, 5, 2, 3, 2, 3]
})
df=pd.DataFrame(data)
print(df)

             flavor  scoops  price
0   white chocolate       1    2.0
1           vanilla       1    1.5
2    dark chocolate       2    3.0
3        strawberry       1    2.0
4        strawberry       3    4.0
5           vanilla       2    2.0
6              mint       1    4.0
7              mint       2    5.0
8   white chocolate       3    2.0
9    dark chocolate       3    3.0
10  white chocolate       2    2.0
11   dark chocolate       5    3.0


**Question 10:** Do the following to the dataframe:
* Create a new collumn ``total_price`` whose value is equal to $scoops * price$*
* Write a function ``groupStatistics(data, groupValue)``. Internally, this function groups ``data``  by ``flavor`` and then returns statistics of a given grouped item ``groupValue`` indexed on the ``total_price`` columns. The statistics is a numpy array contains ``[mean, media, min, max, std]`` of the ``total_price`` column. The ``std`` should be rounded to 2 **decimal places**



In [62]:
import pandas as pd

data = pd.DataFrame({
    'flavor': ['white chocolate', 'vanilla', 'dark chocolate', 'strawberry', 'strawberry', 
               'vanilla', 'mint', 'mint', 'white chocolate', 'dark chocolate', 
               'white chocolate', 'dark chocolate'],
    'scoops': [1, 1, 2, 1, 3, 2, 1, 2, 3, 3, 2, 5],
    'price': [2, 1.5, 3, 2, 4, 2, 4, 5, 2, 3, 2, 3]
})

# Adding total_price column
data['total_price'] = data['scoops'] * data['price']

# Function to calculate group statistics
def groupStatistics(data, groupValue):
    grouped_data = data.groupby('flavor').get_group(groupValue)
    mean = grouped_data['total_price'].mean()
    median = grouped_data['total_price'].median()
    min_price = grouped_data['total_price'].min()
    std = round(grouped_data['total_price'].std(),2)
    return np.array([mean, median, min_price, std])

# Testing
print(groupStatistics(data, 'strawberry'))
print(groupStatistics(data, 'mint'))

[7.   7.   2.   7.07]
[7.   7.   4.   4.24]


In [63]:
grader.check("q11")

q11 results: All test cases passed!

## Submission

Make sure you have run all cells in your notebook in order before running the cell below, so that all images/graphs appear in the output. The cell below will generate a zip file for you to submit. **Please save before exporting!**

Download the exported ZIP. Take note of the ZIP number and proceed to fill the summer school form

In [65]:
# Save your notebook first, then run this cell to export your submission.
grader.export(pdf=False)